#!/usr/bin/env python3
"""
Extract K-matrix (camera intrinsics) from Depth-Anything-3 NPZ output files.

This script extracts camera intrinsics (K-matrix) from NPZ files generated by
DA3 CLI commands (da3 image, da3 auto, da3 images) when using --export-format mini_npz.

Usage:
    # Extract K-matrix from a single image's NPZ output
    python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output K.txt

    # Extract K-matrix for a specific image index
    python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output K.txt --image-index 0

    # Extract all K-matrices from a batch processing result
    python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output-dir ./K_matrices --batch
"""

import argparse
import sys
from pathlib import Path
import numpy as np


def extract_k_matrix(npz_path: Path, output_path: Path, image_index: int = 0) -> bool:
    """
    Extract K-matrix from NPZ file for a specific image.
    
    Args:
        npz_path: Path to NPZ file containing DA3 results
        output_path: Path to output K-matrix file
        image_index: Index of the image to extract (default: 0 for first image)
    
    Returns:
        True if successful, False otherwise
    """
    # Validate NPZ file exists
    if not npz_path.exists():
        print(f"Error: NPZ file not found: {npz_path}")
        return False
    
    # Validate output directory exists
    output_dir = output_path.parent
    if not output_dir.exists():
        print(f"Creating output directory: {output_dir}")
        output_dir.mkdir(parents=True, exist_ok=True)
    
    # Load NPZ file
    print(f"Loading NPZ file: {npz_path}")
    try:
        data = np.load(str(npz_path))
    except Exception as e:
        print(f"Error: Failed to load NPZ file: {e}")
        return False
    
    # Check if intrinsics exist
    if 'intrinsics' not in data:
        print("Error: 'intrinsics' not found in NPZ file.")
        print(f"Available keys: {list(data.keys())}")
        return False
    
    intrinsics = data['intrinsics']
    print(f"Found intrinsics with shape: {intrinsics.shape}")
    
    # Validate image index
    if image_index >= len(intrinsics):
        print(f"Error: Image index {image_index} out of range (0-{len(intrinsics)-1})")
        return False
    
    # Extract K-matrix for the specified image
    K = intrinsics[image_index]
    
    # Validate K-matrix shape
    if K.shape != (3, 3):
        print(f"Error: Invalid K-matrix shape: {K.shape}, expected (3, 3)")
        return False
    
    # Extract parameters
    fx = float(K[0, 0])
    fy = float(K[1, 1])
    cx = float(K[0, 2])
    cy = float(K[1, 2])
    
    print(f"\nK-matrix for image {image_index}:")
    print(f"  fx (focal length X): {fx:.6f} pixels")
    print(f"  fy (focal length Y): {fy:.6f} pixels")
    print(f"  cx (principal point X): {cx:.6f} pixels")
    print(f"  cy (principal point Y): {cy:.6f} pixels")
    
    # Save K-matrix to file
    print(f"\nSaving K-matrix to: {output_path}")
    np.savetxt(str(output_path), K, fmt='%.6f')
    
    # Verify the saved file
    if output_path.exists():
        print("✓ K-matrix saved successfully!")
        print(f"\nK-matrix (3x3):")
        print(K)
        print(f"\nFile format: Space-separated values, 3 rows x 3 columns")
        return True
    else:
        print(f"Error: Failed to save K-matrix to {output_path}")
        return False


def extract_all_k_matrices(npz_path: Path, output_dir: Path) -> bool:
    """
    Extract all K-matrices from NPZ file and save them individually.
    
    Args:
        npz_path: Path to NPZ file containing DA3 results
        output_dir: Directory to save all K-matrix files
    
    Returns:
        True if successful, False otherwise
    """
    # Validate NPZ file exists
    if not npz_path.exists():
        print(f"Error: NPZ file not found: {npz_path}")
        return False
    
    # Create output directory
    if not output_dir.exists():
        print(f"Creating output directory: {output_dir}")
        output_dir.mkdir(parents=True, exist_ok=True)
    
    # Load NPZ file
    print(f"Loading NPZ file: {npz_path}")
    try:
        data = np.load(str(npz_path))
    except Exception as e:
        print(f"Error: Failed to load NPZ file: {e}")
        return False
    
    # Check if intrinsics exist
    if 'intrinsics' not in data:
        print("Error: 'intrinsics' not found in NPZ file.")
        print(f"Available keys: {list(data.keys())}")
        return False
    
    intrinsics = data['intrinsics']
    num_images = len(intrinsics)
    print(f"Found {num_images} K-matrices in NPZ file")
    
    # Extract and save each K-matrix
    success_count = 0
    for i, K in enumerate(intrinsics):
        # Validate K-matrix shape
        if K.shape != (3, 3):
            print(f"Warning: Invalid K-matrix shape for image {i}: {K.shape}, skipping")
            continue
        
        # Generate output filename
        output_path = output_dir / f"K_{i:04d}.txt"
        
        # Save K-matrix
        try:
            np.savetxt(str(output_path), K, fmt='%.6f')
            print(f"✓ Saved K-matrix {i} to {output_path}")
            success_count += 1
        except Exception as e:
            print(f"Error: Failed to save K-matrix {i}: {e}")
    
    print(f"\n{'='*60}")
    print(f"SUCCESS: Extracted {success_count}/{num_images} K-matrices")
    print(f"Output directory: {output_dir}")
    print(f"{'='*60}")
    
    return success_count > 0


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="Extract K-matrix (camera intrinsics) from Depth-Anything-3 NPZ output files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Extract K-matrix from NPZ file (first image)
  python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output K.txt
  
  # Extract K-matrix for a specific image index
  python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output K.txt --image-index 5
  
  # Extract all K-matrices from batch processing
  python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output-dir ./K_matrices --batch
  
  # After running da3 CLI commands:
  # da3 image photo.jpg --export-dir ./output --export-format mini_npz
  # python estimate_k_matrix.py --npz ./output/exports/mini_npz/results.npz --output K.txt
        """
    )
    
    parser.add_argument(
        '--npz',
        type=str,
        required=True,
        help='Path to NPZ file containing DA3 results (e.g., ./output/exports/mini_npz/results.npz)'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        default=None,
        help='Path to output K-matrix file (for single extraction, e.g., K.txt)'
    )
    
    parser.add_argument(
        '--output-dir',
        type=str,
        default=None,
        help='Directory to save K-matrices (for batch extraction, e.g., ./K_matrices)'
    )
    
    parser.add_argument(
        '--image-index',
        type=int,
        default=0,
        help='Index of the image to extract (default: 0 for first image)'
    )
    
    parser.add_argument(
        '--batch',
        action='store_true',
        help='Extract all K-matrices from the NPZ file (requires --output-dir)'
    )
    
    args = parser.parse_args()
    
    # Convert to Path objects
    npz_path = Path(args.npz).resolve()
    
    # Validate arguments
    if args.batch:
        if args.output_dir is None:
            print("Error: --output-dir is required when using --batch")
            return 1
        output_dir = Path(args.output_dir).resolve()
        success = extract_all_k_matrices(npz_path, output_dir)
    else:
        if args.output is None:
            print("Error: --output is required when not using --batch")
            return 1
        output_path = Path(args.output).resolve()
        success = extract_k_matrix(npz_path, output_path, args.image_index)
    
    if success:
        return 0
    else:
        return 1


if __name__ == '__main__':
    sys.exit(main())
